-- AlterTable
ALTER TABLE "User" ADD COLUMN     "ADRESS" TEXT,
ADD COLUMN     "BANK" TEXT,
ADD COLUMN     "INN" INTEGER,
ADD COLUMN     "MFO" INTEGER,
ADD COLUMN     "OKED" INTEGER,
ADD COLUMN     "PC" INTEGER;
